import { GetAppointmentOptionsResponse } from "@timelish/types";

export const demoBookingOptionsResponse: GetAppointmentOptionsResponse = {
  options: [
    {
      _id: "option-1",
      name: "[DEMO] Standard Consultation",
      description: "A time-based consultation session.",
      durationMin: 30,
      durationMax: 60,
      durationStep: 15,
      pricePerHour: 20,
      isAutoConfirm: "inherit",
      isOnline: false,
      durationType: "flexible",
      staff: [
        { memberId: "member-1" },
        { memberId: "member-2", priceOverride: 25 },
      ],
      addons: [
        {
          _id: "addon-1",
          name: "Extra 15 Minutes",
          description: "Extend your session by 15 minutes.",
          price: 20,
          updatedAt: new Date(),
          organizationId: "organization",
        },
        {
          _id: "addon-2",
          name: "Priority Booking",
          description: "Get priority scheduling for your appointment.",
          price: 10,
          updatedAt: new Date(),
          organizationId: "organization",
        },
        {
          _id: "addon-3",
          name: "Session Recording",
          description: "Receive a recording of your session.",
          price: 15,
          updatedAt: new Date(),
          organizationId: "organization",
        },
      ],
      requireDeposit: "inherit",
      updatedAt: new Date(),
      organizationId: "organization",
    },
    {
      _id: "option-2",
      name: "[DEMO] Premium Consultation",
      description: "A 60-minute in-depth consultation.",
      duration: 60,
      price: 90,
      durationType: "fixed",
      isAutoConfirm: "inherit",
      isOnline: false,
      addons: [
        {
          _id: "addon-1",
          name: "Extra 15 Minutes",
          description: "Extend your session by 15 minutes.",
          price: 20,
          updatedAt: new Date(),
          organizationId: "organization",
        },
        {
          _id: "addon-2",
          name: "Priority Booking",
          description: "Get priority scheduling for your appointment.",
          price: 10,
          updatedAt: new Date(),
          organizationId: "organization",
        },
        {
          _id: "addon-3",
          name: "Session Recording",
          description: "Receive a recording of your session.",
          price: 15,
          updatedAt: new Date(),
          organizationId: "organization",
        },
      ],
      organizationId: "organization",
      requireDeposit: "inherit",
      updatedAt: new Date(),
    },
    {
      _id: "option-3",
      name: "[DEMO] Follow-up Session",
      description: "A 20-minute follow-up appointment.",
      duration: 20,
      price: 30,
      durationType: "fixed",
      isAutoConfirm: "inherit",
      isOnline: false,
      addons: [
        {
          _id: "addon-1",
          name: "Extra 15 Minutes",
          description: "Extend your session by 15 minutes.",
          price: 20,
          updatedAt: new Date(),
          organizationId: "organization",
        },
        {
          _id: "addon-2",
          name: "Priority Booking",
          description: "Get priority scheduling for your appointment.",
          price: 10,
          updatedAt: new Date(),
          organizationId: "organization",
        },
        {
          _id: "addon-3",
          name: "Session Recording",
          description: "Receive a recording of your session.",
          price: 15,
          updatedAt: new Date(),
          organizationId: "organization",
        },
      ],
      requireDeposit: "inherit",
      updatedAt: new Date(),
      organizationId: "organization",
    },
  ],
  fieldsSchema: {},
  showPromoCode: true,
  members: [
    {
      id: "member-1",
      name: "[DEMO] Alex Morgan",
      bio: "Senior specialist with 8 years of experience.",
      image: null,
    },
    {
      id: "member-2",
      name: "[DEMO] Jamie Lee",
      bio: "Loves helping clients feel their best.",
      image: null,
    },
  ],
};
