import { BillingPlanTier, NavItemGroup } from "@hacado/types";
import {
  ArrowDownToLine,
  BadgeDollarSign,
  Blocks,
  BookUser,
  Boxes,
  Building,
  CalendarClock,
  CalendarFold,
  CalendarRange,
  ChartArea,
  CircleDollarSign,
  Code2,
  Gift,
  Globe,
  Grid2X2Plus,
  HandPlatter,
  LayoutDashboard,
  LayoutTemplate,
  MailSearch,
  Paintbrush,
  PanelBottom,
  PanelTop,
  Paperclip,
  Send,
  Settings,
  Store,
  TextCursorInput,
  UserRound,
  Users,
  Wallet,
} from "lucide-react";

export const navItems: NavItemGroup[] = [
  {
    id: "overview",
    title: "admin.navigation.overview",
    children: [
      {
        id: "dashboard",
        title: "admin.navigation.dashboard",
        href: "/dashboard",
        icon: <LayoutDashboard />,
        label: "admin.navigation.dashboard",
      },
    ],
  },
  {
    id: "appointments",
    title: "admin.navigation.appointments",
    children: [
      {
        id: "appointments",
        title: "admin.navigation.appointments",
        href: "/dashboard/appointments",
        icon: <CalendarFold />,
        label: "admin.navigation.appointments",
        notificationsCountKey: "pending_appointments",
      },
      {
        id: "schedule",
        title: "admin.navigation.schedule",
        icon: <CalendarRange />,
        requiredPermission: { resource: "schedule", action: "update" },
        items: [
          {
            id: "schedule-base",
            title: "admin.navigation.defaultSchedule",
            href: "/dashboard/settings/schedule",
            label: "admin.navigation.defaultSchedule",
            icon: <CalendarRange />,
            requiredPermission: { resource: "schedule", action: "update" },
          },
        ],
      },
      {
        id: "services",
        title: "admin.navigation.services",
        icon: <HandPlatter />,
        requiredPermission: { resource: "service", action: "read" },
        items: [
          {
            id: "services-fields",
            title: "admin.navigation.fields",
            href: "/dashboard/services/fields",
            label: "admin.navigation.fields",
            icon: <TextCursorInput />,
            requiredPermission: { resource: "service", action: "update" },
          },
          {
            id: "services-addons",
            title: "admin.navigation.addons",
            href: "/dashboard/services/addons",
            label: "admin.navigation.addons",
            icon: <Grid2X2Plus />,
            requiredPermission: { resource: "service", action: "update" },
          },
          {
            id: "services-options",
            title: "admin.navigation.options",
            href: "/dashboard/services/options",
            label: "admin.navigation.options",
            icon: <HandPlatter />,
            requiredPermission: { resource: "service", action: "update" },
          },
          {
            id: "discounts",
            title: "admin.navigation.discounts",
            href: "/dashboard/services/discounts",
            label: "admin.navigation.discounts",
            icon: <BadgeDollarSign />,
            minimumPlanTier: BillingPlanTier.Solo,
            requiredPermission: { resource: "discount", action: "read" },
          },
          {
            id: "gift-cards",
            title: "admin.navigation.giftCards",
            href: "/dashboard/services/gift-cards",
            label: "admin.navigation.giftCards",
            icon: <Gift />,
            minimumPlanTier: BillingPlanTier.Solo,
            requiredPermission: { resource: "giftCard", action: "read" },
          },
        ],
      },
    ],
  },
  {
    id: "financials",
    title: "admin.navigation.financials",
    minimumPlanTier: BillingPlanTier.Solo,
    requiredPermission: { resource: "billing", action: "read" },
    children: [
      {
        id: "financials-overview",
        title: "admin.navigation.financialOverview",
        href: "/dashboard/financials/overview",
        icon: <ChartArea />,
        label: "admin.navigation.financialOverview",
        requiredPermission: { resource: "billing", action: "read" },
      },
      {
        id: "payments",
        title: "admin.navigation.payments",
        href: "/dashboard/financials/payments",
        icon: <CircleDollarSign />,
        label: "admin.navigation.payments",
        requiredPermission: { resource: "billing", action: "read" },
      },
      {
        id: "payments-inbox",
        title: "admin.navigation.paymentsInbox",
        href: "/dashboard/financials/inbox",
        icon: <Wallet />,
        label: "admin.navigation.paymentsInbox",
        notificationsCountKey: "synced_payments_review",
        requiredPermission: { resource: "syncedPayment", action: "read" },
      },
    ],
  },
  {
    id: "customers",
    title: "admin.navigation.customers",
    children: [
      {
        id: "customers",
        title: "admin.navigation.customers",
        href: "/dashboard/customers",
        icon: <BookUser />,
        label: "admin.navigation.customers",
        requiredPermission: { resource: "customer", action: "read" },
      },
    ],
  },
  {
    id: "website",
    title: "admin.navigation.website",
    children: [
      {
        id: "pages",
        title: "admin.navigation.pages",
        href: "/dashboard/pages",
        icon: <Globe />,
        label: "admin.navigation.pages",
        requiredPermission: { resource: "page", action: "read" },
      },
      {
        id: "assets",
        title: "admin.navigation.assets",
        href: "/dashboard/assets",
        icon: <Paperclip />,
        label: "admin.navigation.assets",
        requiredPermission: { resource: "page", action: "read" },
      },

      {
        id: "appearance",
        title: "admin.navigation.appearance",
        icon: <Paintbrush />,
        requiredPermission: { resource: "page", action: "read" },
        items: [
          {
            id: "appearence-scripts",
            title: "admin.navigation.scripts",
            href: "/dashboard/appearence/scripts",
            icon: <Code2 />,
            label: "admin.navigation.scripts",
            minimumPlanTier: BillingPlanTier.Solo,
            requiredPermission: { resource: "settings", action: "update" },
          },
          {
            id: "appearance-page-headers",
            title: "admin.navigation.pageHeaders",
            href: "/dashboard/pages/headers",
            icon: <PanelTop />,
            label: "admin.navigation.pageHeaders",
            requiredPermission: { resource: "page", action: "update" },
          },
          {
            id: "appearance-page-footers",
            title: "admin.navigation.pageFooters",
            href: "/dashboard/pages/footers",
            icon: <PanelBottom />,
            label: "admin.navigation.pageFooters",
            requiredPermission: { resource: "page", action: "update" },
          },
        ],
      },
    ],
  },
  {
    id: "settings",
    title: "admin.navigation.settings",
    children: [
      {
        id: "settings",
        title: "admin.navigation.settings",
        icon: <Settings />,
        requiredPermission: { resource: "settings", action: "read" },
        items: [
          {
            id: "settings-brand",
            title: "admin.navigation.brand",
            href: "/dashboard/settings/brand",
            icon: <Building />,
            label: "admin.navigation.brand",
            requiredPermission: { resource: "settings", action: "update" },
          },
          {
            id: "settings-team",
            title: "admin.navigation.team",
            href: "/dashboard/settings/team",
            icon: <Users />,
            label: "admin.navigation.team",
            requiredPermission: { resource: "team", action: "invite" },
          },
          {
            id: "settings-appointments",
            title: "admin.navigation.appointments",
            href: "/dashboard/settings/appointments",
            icon: <CalendarClock />,
            label: "admin.navigation.appointments",
            requiredPermission: { resource: "settings", action: "update" },
          },
          {
            id: "settings-customer-access",
            title: "admin.navigation.customerAccess",
            href: "/dashboard/settings/customer-access",
            icon: <UserRound />,
            label: "admin.navigation.customerAccess",
            requiredPermission: { resource: "settings", action: "update" },
          },
        ],
      },

      {
        id: "communications",
        icon: <Send />,
        title: "admin.navigation.communications",
        items: [
          {
            id: "templates",
            title: "admin.navigation.templates",
            href: "/dashboard/templates",
            icon: <LayoutTemplate />,
            label: "admin.navigation.templates",
            requiredPermission: {
              resource: "communication",
              action: "readAll",
            },
          },
          {
            id: "communications-logs",
            title: "admin.navigation.logs",
            href: "/dashboard/communication-logs",
            icon: <MailSearch />,
            label: "admin.navigation.communicationLogs",
            requiredPermission: { resource: "communication", action: "read" },
          },
        ],
      },
      {
        id: "apps",
        title: "admin.navigation.apps",
        icon: <Blocks />,
        label: "admin.navigation.apps",
        items: [
          {
            id: "apps-installed",
            title: "admin.navigation.installedApps",
            href: "/dashboard/apps",
            icon: <ArrowDownToLine />,
            label: "admin.navigation.installedApps",
          },
          {
            id: "apps-store",
            title: "admin.navigation.store",
            href: "/dashboard/apps/store",
            icon: <Store />,
            label: "admin.navigation.store",
          },
          {
            id: "apps-default",
            title: "admin.navigation.defaultApps",
            href: "/dashboard/apps/default",
            icon: <Boxes />,
            label: "admin.navigation.defaultApps",
            requiredPermission: { resource: "app", action: "useCompany" },
          },
        ],
      },
    ],
  },
];
